
MARIADB_HOST=${DATABASE_HOST:-localhost}
MARIADB_USER=${DATABASE_USER:-webird}
MARIADB_PASSWORD=${DATABASE_PASSWORD:-open}

PHP_VERSION=${PHP_VERSION:-7.2}
PHP_ETC=${PHP_ETC:-/etc/php/$PHP_VERSION}
NGINX_ETC=${NGINX_ETC:-/etc/nginx}

DEBIAN_FRONTEND=${DEBIAN_FRONTEND:-noninteractive}

WEB_DOMAIN_DEVELOPMENT=${WEB_DOMAIN_DEVELOPMENT:-$dev.webird.io}
WEB_DOMAIN_PRODUCTION=${WEB_DOMAIN_PRODUCTION:-$dist.webird.io}