'use strict'

import 'jquery'
import 'bootstrap/js/transition.js'
import 'bootstrap/js/alert.js'
import 'bootstrap/js/button.js'
import 'bootstrap/js/carousel.js'
import 'bootstrap/js/collapse.js'
import 'bootstrap/js/dropdown.js'
import 'bootstrap/js/modal.js'
import 'bootstrap/js/tooltip.js'
import 'bootstrap/js/popover.js'
import 'bootstrap/js/scrollspy.js'
import 'bootstrap/js/tab.js'
import 'bootstrap/js/affix.js'
